server:
  port: 1203
  
logging:
  level:
    org.springframework: ERROR
    com.travel: DEBUG
    org.keycloak: DEBUG
    
 
 
    
spring:
  devtools:
    restart:
      enabled: true  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
            implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql : true
eserv :
  datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.178.10.104:3306/e_services?useSSL=false&useSSL=false
        username: root
        password: Care@3210
cpuser :
  datasource :
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.178.10.104:3306/e-services-cp-users?useSSL=false
        username: root
        password: Care@3210
  
     
    
    
cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-south-1
    credentials:
      accessKey: AKIA4COQRGUFPYAJC2N3
      secretKey: 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
com:
  travel: 
    travtronics:
      uploader:
        bucketName: travtronics-altxmed
      cdn:
        url: https://d2prwoxphqiek7.cloudfront.net/
keycloak:
  auth-server-url: http://192.178.10.104:8080/auth
  realm: Eservices
  resource: eservice-app
  public-client: true
  security-constraints:
  - auth-roles:
    - AdminRole
    security-collections:
    - patterns:
      - /login-management
  ssl-required: none
  use-resource-role-mappings: true
debug: true


